// Seed templates data — used as default until DB is set up
export const TEMPLATES = [
  {
    id: 'traditional-gold',
    name: 'Kanchipuram Gold',
    category: 'Traditional',
    description: 'A timeless South Indian invitation inspired by Kanchipuram silk sarees — rich maroon, gold borders and classical motifs.',
    preview_names: 'Arjun & Priya',
    preview_sub: 'Together with their families',
    preview_date: 'December 12, 2025',
    bg_gradient: 'linear-gradient(150deg, #5A0000 0%, #800000 50%, #3D0000 100%)',
    features: ['Live Countdown', 'Events Timeline', 'RSVP Form'],
    is_premium: false,
    colors: {
      primary: '#800000',
      secondary: '#D4AF37',
      bg: '#FFF5E1',
      text: '#1A0A00',
    },
    template_json: {
      title: '{{groom}} weds {{bride}}',
      subtitle: 'Together with their families',
      event_label: 'Auspicious Muhurtham',
    },
  },
  {
    id: 'royal-lotus',
    name: 'Royal Lotus',
    category: 'Royal',
    description: 'An opulent royal-style invitation with lotus motifs, deep burgundy tones and golden calligraphy — perfect for grand celebrations.',
    preview_names: 'Vikram & Ananya',
    preview_sub: 'Request the honour of your presence',
    preview_date: 'January 18, 2026',
    bg_gradient: 'linear-gradient(150deg, #1A0A2E 0%, #3D1278 50%, #1A0A2E 100%)',
    features: ['Photo Gallery', 'Music Autoplay', 'Guest Personalization'],
    is_premium: true,
    colors: {
      primary: '#4A0E8F',
      secondary: '#D4AF37',
      bg: '#0D0824',
      text: '#F5E6FF',
    },
    template_json: {
      title: '{{groom}} & {{bride}}',
      subtitle: 'Request the honour of your presence',
      event_label: 'Wedding Ceremony',
    },
  },
  {
    id: 'floral-jasmine',
    name: 'Jasmine Garden',
    category: 'Floral',
    description: 'A fresh, fragrant floral design featuring delicate jasmine patterns with a soft green and gold palette for the modern couple.',
    preview_names: 'Karthik & Deepa',
    preview_sub: 'With joyful hearts',
    preview_date: 'February 22, 2026',
    bg_gradient: 'linear-gradient(150deg, #1B3A1E 0%, #2E7D32 50%, #1B3A1E 100%)',
    features: ['Live Countdown', 'Google Maps', 'RSVP Form'],
    is_premium: false,
    colors: {
      primary: '#2E7D32',
      secondary: '#D4AF37',
      bg: '#F1F8E9',
      text: '#1B3A1E',
    },
    template_json: {
      title: '{{groom}} & {{bride}}',
      subtitle: 'With joyful hearts, they invite you',
      event_label: 'Sacred Union',
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'Modern',
    description: 'A sleek, minimalist invitation with clean typography, subtle textures and a sophisticated monochromatic palette.',
    preview_names: 'Rahul & Sneha',
    preview_sub: 'Are getting married',
    preview_date: 'March 8, 2026',
    bg_gradient: 'linear-gradient(150deg, #1C1C1C 0%, #2D2D2D 50%, #1C1C1C 100%)',
    features: ['Video Integration', 'RSVP Analytics', 'Guest List'],
    is_premium: true,
    colors: {
      primary: '#1C1C1C',
      secondary: '#D4AF37',
      bg: '#F8F8F8',
      text: '#1C1C1C',
    },
    template_json: {
      title: '{{groom}} & {{bride}}',
      subtitle: 'Are getting married',
      event_label: 'Wedding Day',
    },
  },
];
